
project_id = "ietvubimwsfugzkiycus"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
url = "http://localhost:54321"

[realtime]
enabled = true

[functions.check-territory-availability]
verify_jwt = true

[functions.create-admin-lead]
verify_jwt = true
