
project_id = "ietvubimwsfugzkiycus"

[functions.notify-lead]
verify_jwt = true

[functions.test-sms]
verify_jwt = true

[functions.admin-notification]
verify_jwt = true

[functions.contact-support]
verify_jwt = true

[functions.update-lead]
verify_jwt = true
