
# This file defines configuration for Supabase Functions
[functions]

[functions.get-all-users]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.ensure-profile]
verify_jwt = false

[functions.set-admin]
verify_jwt = true

[functions.admin-notification]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.create-territory]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.notify-lead]
verify_jwt = true

[functions.schedule-followup-email]
verify_jwt = false

[functions.send-followup-email]
verify_jwt = true

[functions.welcome-email]
verify_jwt = true
