
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ietvubimwsfugzkiycus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlldHZ1Ymltd3NmdWd6a2l5Y3VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0Mjk1MzEsImV4cCI6MjA2MzAwNTUzMX0.3zKcZZnJLdvnoaZ2xq2Gwstx6BoXrPsYBwObOeQnyhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a retry function for better network resilience
const createClientWithRetry = () => {
  try {
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
        storageKey: 'leadxclusive-auth-token',
        storage: typeof window !== 'undefined' ? window.localStorage : undefined,
        detectSessionInUrl: false,
        flowType: 'pkce'
      },
      global: {
        // Add additional headers for better compatibility
        headers: {
          'X-Client-Info': 'leadxclusive-web'
        }
      }
    });
  } catch (e) {
    console.error('Error creating Supabase client, retrying...', e);
    // If we fail to create the client, we'll just return a minimal implementation
    // that won't cause the entire app to crash
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
  }
};

export const supabase = createClientWithRetry();
