// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ietvubimwsfugzkiycus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlldHZ1Ymltd3NmdWd6a2l5Y3VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0Mjk1MzEsImV4cCI6MjA2MzAwNTUzMX0.3zKcZZnJLdvnoaZ2xq2Gwstx6BoXrPsYBwObOeQnyhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);